"""Config loader for the bridge.

Reads /etc/hermes-voice-bridge/config.toml (or the path in
HERMES_VOICE_BRIDGE_CONFIG). The file is generated by install.sh.

Schema:
    [bridge]
    host = "0.0.0.0"
    port = 8765
    token = "<base64url 32-byte secret>"

    [hermes]
    base_url = "http://localhost:8642"
    request_timeout = 30
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

try:
    import tomllib  # type: ignore[import-not-found]
except ImportError:  # pragma: no cover - py3.10
    import tomli as tomllib  # type: ignore[no-redef]

DEFAULT_CONFIG_PATH = "/etc/hermes-voice-bridge/config.toml"


@dataclass(frozen=True)
class BridgeConfig:
    host: str
    port: int
    token: str
    hermes_base_url: str
    hermes_request_timeout: int

    @classmethod
    def from_dict(cls, data: dict) -> "BridgeConfig":
        bridge = data.get("bridge", {})
        hermes = data.get("hermes", {})
        token = bridge.get("token")
        if not token:
            raise ValueError("bridge.token is required")
        return cls(
            host=bridge.get("host", "0.0.0.0"),
            port=int(bridge.get("port", 8765)),
            token=str(token),
            hermes_base_url=str(hermes.get("base_url", "http://localhost:8642")),
            hermes_request_timeout=int(hermes.get("request_timeout", 30)),
        )

    @classmethod
    def from_file(cls, path: Optional[str] = None) -> "BridgeConfig":
        candidate = path or os.environ.get("HERMES_VOICE_BRIDGE_CONFIG") or DEFAULT_CONFIG_PATH
        text = Path(candidate).read_text(encoding="utf-8")
        return cls.from_dict(tomllib.loads(text))
